/**
  * copy from https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/translate-survey/#SpecifyingTheParticipantLanguage
 **/
export default [
    { "lang": "Albanian", "code": "SQI" },
    { "lang": "Arabic", "code": "AR" },
    { "lang": "Armenian", "code": "HYE" },
    { "lang": "Assamese", "code": "ASM" },
    { "lang": "Azeri/Azerbaijani (Latin script)", "code": "AZ-AZ" },
    { "lang": "Bahasa Indonesia", "code": "ID" },
    { "lang": "Bahasa Malaysia", "code": "MS" },
    { "lang": "Belarusian", "code": "BEL" },
    { "lang": "Bengali", "code": "BN" },
    { "lang": "Bosnian", "code": "BS" },
    { "lang": "Brazilian Portuguese", "code": "PT-BR" },
    { "lang": "Bulgarian", "code": "BG" },
    { "lang": "Catalan", "code": "CA" },
    { "lang": "Cebuano", "code": "CEB" },
    { "lang": "Chinese (Simplified)", "code": "ZH-S" },
    { "lang": "Chinese (Traditional)", "code": "ZH-T" },
    { "lang": "Croatian", "code": "HR" },
    { "lang": "Czech", "code": "CS" },
    { "lang": "Danish", "code": "DA" },
    { "lang": "Dutch", "code": "NL" },
    { "lang": "English – UK", "code": "EN-GB" },
    { "lang": "English – US", "code": "EN" },
    { "lang": "Esperanto", "code": "EO" },
    { "lang": "Estonian", "code": "ET" },
    { "lang": "Finnish", "code": "FI" },
    { "lang": "French", "code": "FR" },
    { "lang": "French Canadian", "code": "FR-CA" },
    { "lang": "Georgian", "code": "KAT" },
    { "lang": "German", "code": "DE" },
    { "lang": "Greek", "code": "EL" },
    { "lang": "Gujarati", "code": "GU" },
    { "lang": "Hebrew", "code": "HE" },
    { "lang": "Hindi", "code": "HI" },
    { "lang": "Hungarian", "code": "HU" },
    { "lang": "Icelandic", "code": "ISL" },
    { "lang": "Ilonggo/Hiligaynon", "code": "HIL" },
    { "lang": "Italian", "code": "IT" },
    { "lang": "Japanese", "code": "JA" },
    { "lang": "Kannada", "code": "KAN" },
    { "lang": "Kazakh (Cyrilic)", "code": "KAZ" },
    { "lang": "Khmer", "code": "KM" },
    { "lang": "Korean", "code": "KO" },
    { "lang": "Latvian", "code": "LV" },
    { "lang": "Lithuanian", "code": "LT" },
    { "lang": "Macedonian", "code": "MK" },
    { "lang": "Malayalam", "code": "MAL" },
    { "lang": "Marathi", "code": "MAR" },
    { "lang": "Mongolian", "code": "MN" },
    { "lang": "Montenegrin", "code": "SR-ME" },
    { "lang": "Myanmar/Burmese", "code": "MY" },
    { "lang": "Norwegian", "code": "NO" },
    { "lang": "Odia/Oriya", "code": "ORI" },
    { "lang": "Persian", "code": "FA" },
    { "lang": "Polish", "code": "PL" },
    { "lang": "Portuguese", "code": "PT" },
    { "lang": "Punjabi", "code": "PA-IN" },
    { "lang": "Romanian", "code": "RO" },
    { "lang": "Russian", "code": "RU" },
    { "lang": "Serbian", "code": "SR" },
    { "lang": "Sinhalese", "code": "SIN" },
    { "lang": "Slovak", "code": "SK" },
    { "lang": "Slovenian", "code": "SL" },
    { "lang": "Spanish EU", "code": "ES-ES" },
    { "lang": "Spanish LATAM", "code": "ES" },
    { "lang": "Swahili", "code": "SW" },
    { "lang": "Swedish", "code": "SV" },
    { "lang": "Tagalog", "code": "TGL" },
    { "lang": "Tamil", "code": "TA" },
    { "lang": "Telugu", "code": "TEL" },
    { "lang": "Thai", "code": "TH" },
    { "lang": "Turkish", "code": "TR" },
    { "lang": "Ukrainian", "code": "UK" },
    { "lang": "Urdu", "code": "UR" },
    { "lang": "Vietnamese", "code": "VI" },
    { "lang": "Welsh", "code": "CY" }
]
